### ISSUE TITLE
Typo en el texto de introducción

### ISSUE THREAD

**Issue by luis-alvarez** [odoo-l10n-ar/odoo-l10n-ar.github.io#10]
2do párrafo, 3er horación dice:
La respuesta más fácil sería porqué es necesario.
Debería decir:
La respuesta más fácil sería porque es necesario.

**Comment by csrocha** [comment]
Luis, el texto va a cambiar en los próximos días si se acepta como localización oficial. Gracias igual!

**Comment by luis-alvarez** [comment]
Ahh! ok ok! No problem! Gracias, sólo estaba viendo esto y me gustó la idea de probar el workflow! Saludos!
