### ISSUE TITLE
Revertir un commit desde la web

### ISSUE THREAD

**Issue by jjscarafia** [odoo-l10n-ar/odoo-l10n-ar.github.io#4]
Cristian, alguna idea en como debería proceder para revertir el commit que hice con la propuesta del PR que hice antes?
Se me ocurre:
1. Borrar el fork y crear uno nuevo (mala idea)
2. Descargar mi fork y luego supongo que un "git reset --hard ..." y luego "git push --force"
Se te ocurre alguna forma mejor? Algo directamente desde la web?

**Comment by csrocha** [comment]
Prueba con esto:
https://github.com/blog/1857-introducing-the-revert-button

Recuerda de hacer un update luego, pero creo que no lo podés hacer online.

Aunque mira lo siguiente que puede ayudarte a decidirte entre las dos opciones

https://help.github.com/articles/github-flow-in-the-browser

**Comment by csrocha** [comment]
Juan, lograste revertir el repositorio? Si es así, por favor cerrar el issue.

**Comment by jjscarafia** [comment]
Cristian, estuve viendo cono hacerlo y me di cuenta que neceaitaba estudiar
git. Vengo un poco demorado pero ya voy a responder a estoy a las otras
cosas que mandaste. Muy buen laburo!

**Comment by jjscarafia** [comment]
Por lo que estuve viendo no puedo revertir el repo online, tuve que clonar y hacer un revert. Pero después quise hacer un sync y desde el original (lo mio es un fork) y no me funciono del todo. Igual ahí hice un nuevo fork, la prox saldrá..
