### ISSUE TITLE
Sabores. Que hacemos?

### ISSUE THREAD

**Issue by jjscarafia** [odoo-l10n-ar/odoo-l10n-ar.github.io#5]
Cristian, como te parece que hagamos entonces con lo del l10n_ar_invoice propuesto por nos? Hacemos renombrado por colores entonces? Hago todas las mods en un fork y luego un PR?

**Comment by csrocha** [comment]
Juan,

Has el color en un repositorio tuyo. Asignale un color al nombre y luego
crea un caso en requisitos (lee este punto en el README de requisitos)

Una vez aceptado solo habrá  que reasignarle el owner desde propiedades del
repositorio.

Abrazo,
Cristián.
